Traceback (most recent call last):
  File "/Users/eatai/.pyenv/versions/3.13.1/envs/datascience/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/Users/eatai/.pyenv/versions/3.13.1/envs/datascience/lib/python3.13/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/eatai/.pyenv/versions/3.13.1/envs/datascience/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Users/eatai/.pyenv/versions/3.13.1/lib/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/eatai/.pyenv/versions/3.13.1/envs/datascience/lib/python3.13/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/Users/eatai/.pyenv/versions/3.13.1/envs/datascience/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/eatai/.pyenv/versions/3.13.1/envs/datascience/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# In a code cell, anything that comes after a # is comment. We use comments to explain our code or leave love letters to our future selves.
# You'll be surprised just how quickly you forget what you were thinking when you originally wrote code, so help yourself out and comment.
# When your code runs, comments are ignored; it's just for humans.

# Let's introduce some math operators.

# Addition and subtraction
a = 4 + 5
b = 111-99

print(f'a = {a}\nb = {b}')

# Multiplication and division
c = 5 * 4
d = 20/4

print(f'd = {d}\ne = {e}')

# Exponentiation
e = 0.5**2

print(f'c = {c}')

# Run the cell with SHIFT+ENTER

------------------

----- stdout -----
a = 9
b = 12
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 17[0m
[1;32m     14[0m c [38;5;241m=[39m [38;5;241m5[39m [38;5;241m*[39m [38;5;241m4[39m
[1;32m     15[0m d [38;5;241m=[39m [38;5;241m20[39m[38;5;241m/[39m[38;5;241m4[39m
[0;32m---> 17[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;124md = [39m[38;5;132;01m{[39;00md[38;5;132;01m}[39;00m[38;5;130;01m\n[39;00m[38;5;124me = [39m[38;5;132;01m{[39;00m[43me[49m[38;5;132;01m}[39;00m[38;5;124m'[39m)
[1;32m     19[0m [38;5;66;03m# Exponentiation[39;00m
[1;32m     20[0m e [38;5;241m=[39m [38;5;241m0.5[39m[38;5;241m*[39m[38;5;241m*[39m[38;5;241m2[39m

[0;31mNameError[0m: name 'e' is not defined

