Traceback (most recent call last):
  File "/Users/eatai/.pyenv/versions/3.9.21/envs/tf/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/eatai/.pyenv/versions/3.9.21/envs/tf/lib/python3.9/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/eatai/.pyenv/versions/3.9.21/envs/tf/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/eatai/.pyenv/versions/3.9.21/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/eatai/.pyenv/versions/3.9.21/envs/tf/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/eatai/.pyenv/versions/3.9.21/envs/tf/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/eatai/.pyenv/versions/3.9.21/envs/tf/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
feature_names = list(macros_df.columns)
ss = StandardScaler()

X = ss.fit_transform(macros_df)
fig, ax = plotPCA(X, feature_names = feature_names)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[11], line 5[0m
[1;32m      2[0m ss [38;5;241m=[39m StandardScaler()
[1;32m      4[0m X [38;5;241m=[39m ss[38;5;241m.[39mfit_transform(macros_df)
[0;32m----> 5[0m fig, ax [38;5;241m=[39m plotPCA(X, feature_names [38;5;241m=[39m feature_names)

[0;31mValueError[0m: too many values to unpack (expected 2)

